name: Build Flarial and UPLOAD to newcdn
on:
  
  push:
    branches: [ "main","scripting-v2" ]
  pull_request:
    branches: [ "main","scripting-v2" ]

  workflow_dispatch:

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: "Check if build commit"
      run: |
        
        if ( "${{ github.event.head_commit.message }}" -like "*build:*" )
        {echo "Continuing to build"}
        else 
        {
        echo "Not a build commit, exiting"
        exit 0
        }
        
    - name: Set Up MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1

    
    - name: Configure CMake
      run: |
        cmake -S . -B build -G "Ninja" -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_STANDARD=23 -DCMAKE_BUILD_TYPE=Release

    
    - name: Build DLL
      run: |
          cmake --build build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
        name: Flarial_DLL
        path: D:\a\dll\dll\build\Flarial.dll
  
  upload-to-cdn:
    runs-on: ubuntu-latest
    needs: windows-build
    steps:
      
        - name: checkkout cdn
          uses: actions/checkout@v4
          with:
            repository: 'TTF-fog/newcdn'
            ref: 'main'
            token:  ${{secrets.ACTIONS_GITHUB_TOKEN}}
        - name: setup git config
          run: |
            git config user.name "GitHub Actions Bot"
            git config user.email "actions@example.com"
        - name: Download dll
          uses: actions/download-artifact@v4.1.9
        - name: push changes
          run: |
            name="Nightly_${GITHUB_SHA:0:6}_Add:$(echo '${{ github.event.head_commit.message }}')"
            echo $name
            mv ./Flarial_DLL "./$name"
            ls
            git add $name
            git commit -m "Add Nightly for Build Commit: '${{ github.event.head_commit.message }}'"
            git push origin main

       
